logging:
  level:
    root: info
    kr.co.lotteOn: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

    #jasypt:
    #encryptor:
    #password: ${JASYPT_ENCRYPTOR_PASSWORD}
    #algorithm: PBEWithMD5AndDES
    #bean: jasyptStringEncryptor
file:
  upload:
    path: uploads

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080
  servlet:
    context-path: /

jwt:
  issuer: chhak0503@gmail.com
  secret: 1XudNUpSmog5lwI9thJFejF6YfBBQnCI

spring:
  servlet:
    multipart:
      location: uploads
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: clsrntkdgh@gmail.com
    password: redohcjnlkzeagdo
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  application:
    name: J2SM
    version: SNAPSHOT

  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    cache: false

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://3.34.124.218:3306/J2SM #?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: J2SM
    password: rkaaks98Q!
    driver-class-name: com.mysql.cj.jdbc.Driver

    logging:
      level:
        com.zaxxer.hikari.HikariConfig: DEBUG
        com.zaxxer.hikari: TRACE

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: false


#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: false
#    open-in-view: false
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true


