server:
  port: 8080
  servlet:
    context-path: /

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  servlet:
    multipart:
      location: uploads
      max-file-size: 10MB

  cache:
    type: redis

  data:
    mongodb:
      uri: mongodb://root:1234@3.34.124.218:27017/mydb?authSource=admin

    redis:
      host: 43.201.101.104
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  mail:
    host: smtp.gmail.com
    port: 587
    username: wnstj050505@gmail.com
    password: yhrh mdjx drdo ithj
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  application:
    name: J2SM
    version: 0.0.1-SNAPSHOT

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  devtools:
    restart:
      enabled: true       # 개발 중이므로 유지
    livereload:
      enabled: false      # 느려질 수 있으니 끔

  datasource:
    url: jdbc:mysql://3.34.124.218:3306/J2SM
    username: J2SM
    password: rkaaks98Q!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update     # 개발 중에는 허용
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true         # 개발 중에는 유용
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

file:
  upload:
    path: uploads

jwt:
  issuer: chhak0503@gmail.com
  secret: 1XudNUpSmog5lwI9thJFejF6YfBBQnCI

logging:
  level:
    root: info
    kr.co.lotteOn: debug
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: off
    org.springframework.data.redis.connection: DEBUG
    io.lettuce.core: DEBUG

# 카카오 페이
kakao:
  ADMIN_KEY: ENC("5k9pl/My89+oJP1TFdbe+o9Y9IzMUEm4ekh1rIp3NunENyFXdCrlS3RnCfdyQVIv")